#!/usr/bin/env bash
set -euo pipefail

# This script runs when we get a new session.
#
# available stuff:
#
# - `$1` is the session description
# - `$2` is the session kind
# - `$3` is the session projected end time
# - `$SESSION` is the json-serialized session

say "starting session ${1:-NO SESSION}"
